# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
        ('clientUsers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='article',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.Article'),
        ),
    ]
