# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 15:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientUsers', '0002_page_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='article',
        ),
    ]
