# Generated by Django 2.0 on 2018-04-04 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientUsers', '0004_page_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuser',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clientuser',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clientuser',
            name='ip_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clientuser',
            name='isp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
