# Generated by Django 2.0 on 2018-04-03 07:32

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171224_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=users.models.upload_location, width_field='width_field'),
        ),
    ]
