# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 15:09
from __future__ import unicode_literals

import articles.models
import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_english', models.CharField(max_length=120)),
                ('title_farsi', models.CharField(max_length=120)),
                ('abstract_english', models.TextField(blank=True, null=True)),
                ('abstract_farsi', models.TextField(blank=True, null=True)),
                ('content_english', ckeditor.fields.RichTextField()),
                ('content_farsi', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=articles.models.upload_location, width_field='width_field')),
                ('width_field', models.IntegerField(default=0)),
                ('height_field', models.IntegerField(default=0)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('view_count', models.IntegerField(default=0, null=True)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='categories.Category')),
                ('tags', models.ManyToManyField(blank=True, to='tags.Tag')),
            ],
            options={
                'ordering': ('created_datetime', 'updated_datetime'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='article',
            unique_together=set([('title_english', 'slug')]),
        ),
    ]
